name: Build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  gogitops:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: GoGitOps Step
      id: gogitops
      uses: beaujr/gogitops-action@v0.2
      with:
        github-actions-token: ${{secrets.GITHUB_TOKEN}}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get gomplate
      uses: wei/wget@v1
      with:
        args: -O gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.11.1/gomplate_linux-amd64
    - name: Set gomplate executable
      run: sudo chmod +x gomplate && sudo mv gomplate /usr/local/bin/gomplate
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/crumbhole/kubecog-plugin:pull
